apiVersion: v1
kind: ConfigMap
metadata:
  name: openttd-user-config
data:
  USER: "daemon"
  UID: "1000"
  GID: "1000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openttd
  labels:
    app: openttd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openttd
  template:
    metadata:
      labels:
        app: openttd
    spec:
      nodeSelector:
        kubernetes.io/hostname: morespace
      securityContext:
            fsGroup:
              valueFrom:
                configMapKeyRef:
                  name: openttd-user-config
                  key: UID
      containers:
        - image: nextek/openttd:latest
          imagePullPolicy: Always
          name: openttd
          securityContext:
            allowPrivilegeEscalation: false
          ports:
          - containerPort: 3979
            name: openttd-tcp
            protocol: TCP
          - containerPort: 3979
            name: openttd-udp
            protocol: UDP
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 521Mi
          env:
            - name: loadgame
              value: "exit"
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: openttd-user-config
                  key: USER
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: openttd-user-config
                  key: UID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: openttd-user-config
                  key: GID
          volumeMounts:
          - name: openttd-config
            mountPath: /home/openttd/.openttd
      volumes:
      - name: openttd-config
        hostPath:
          path: /home/user/.openttd

---
apiVersion: v1
kind: Service
metadata:
  name: openttd
  labels:
    app: openttd
spec:
  selector:
    app: openttd
  ports:
  - name: openttd-tcp
    protocol: TCP
    port: 3979
    targetPort: 3979
  - name: openttd-udp
    protocol: UDP
    port: 3979
    targetPort: 3979
  sessionAffinity: None
  type: NodePort
