name: Docker Tests

on:
  # schedule:
  #   - cron: '40 */6 * * *'
  workflow_dispatch:
    branches: [master]

env:
  GITHUB_REPO: nnaso/openttd_jgrpp


jobs:
  run-test:
    name: Test Docker Image
    strategy:
      matrix:
        include:
          - platform_tag: amd64
            platform: linux/amd64
            runner: [ubuntu-latest]
          - platform_tag: i386
            platform: linux/386
            runner: [ubuntu-latest]
          - platform_tag: arm64
            platform: linux/arm64
            runner: [ubuntu-latest]
          - platform_tag: armv7
            platform: linux/arm/v7
            runner: [ubuntu-latest]
          - platform_tag: armv6
            platform: linux/arm/v6
            runner: [ubuntu-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: |
          docker pull --platform ${{ matrix.platform }} ghcr.io/${{ env.GITHUB_REPO }}:latest

      - name: Docker Run
        run: |
          docker run --platform ${{ matrix.platform }} --init --entrypoint /bin/sh ghcr.io/${{ env.GITHUB_REPO }}:latest  \
          -c 'timeout 5 ./openttd.sh || ( [[ $? -eq 143 ]] && exit 0 )'