name: Platform Tests

on:
  # schedule:
  #   - cron: '40 */6 * * *'
  workflow_run:
    workflows: ["Docker Build Latest (Cross-compile)"]
    types:
      - completed
  workflow_dispatch:
    branches: [master]

env:
  GITHUB_REPO: nnaso/openttd_jgrpp


jobs:
  run-test:
    name: Test Docker Image
    strategy:
      matrix:
        include:
          - platform_tag: amd64
            platform: linux/amd64
            runner: [ubuntu-latest]
          - platform_tag: i386
            platform: linux/386
            runner: [ubuntu-latest]
          - platform_tag: arm64
            platform: linux/arm64
            runner: [ubuntu-latest]
          - platform_tag: armv7
            platform: linux/arm/v7
            runner: [ubuntu-latest]
          - platform_tag: armv6
            platform: linux/arm/v6
            runner: [ubuntu-latest]
            cpu: 'arm1176'
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Pull
        run: |
          docker pull --platform ${{ matrix.platform }} ghcr.io/${{ env.GITHUB_REPO }}:latest

      - name: Docker Run
        run: |
          cpu_arg=''
          if [ ! -z ${{ matrix.cpu }} ] 
            cpu_arg='-e QEMU_CPU=${{ matrix.cpu }}'
          fi

          docker run $cpu_arg --platform ${{ matrix.platform }} --rm --init --entrypoint /bin/sh ghcr.io/${{ env.GITHUB_REPO }}:latest  \
          -c 'arch; (sleep 5; echo "dump_info roadtypes"; sleep 1;  echo "dump_info railtypes"; sleep 1; echo "dump_info cargotypes"; sleep 1; echo "save test_save"; sleep 2; echo "load test_save"; sleep 3; echo "exit" && cat) | ./openttd.sh'